site_name: Pocket TCG Ranked Leaderboard
site_url: https://analyzer-labs.github.io/pocket-tcg-ranked-leaderboard-docs/

# Make it explicit
docs_dir: docs

theme:
  name: material
nav:
  - Home: index.md
  - FAQ: faq.md
  - Guides:
      - Quickstart: guides/quickstart.md
      - Commands: guides/commands.md
      - Leaderboard: guides/leaderboard.md
      - Troubleshooting: guides/troubleshooting.md
  - For Admins:
      - Setup: admin/setup.md
      - Billing: admin/billing.md
  - Legal:
      - Privacy Policy: legal/privacy-policy.md
      - Terms of Service: legal/terms-of-service.md
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets

