site_name: Pocket TCG Ranked Leaderboard
site_url: https://andalyzer-labs.github.io/pocket-tcg-ranked-leaderboard-docs/

# Make it explicit
docs_dir: docs

theme:
  name: material
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Commands: commands.md
  - FAQ: FAQ.md
  - Legal:
      - Privacy Policy: legal/privacy-policy.md
      - Terms of Service: legal/terms-of-service.md
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets





